site_name: Lessons on Data Analysis from CERN

nav:
  - Home: index.md
  - Lectures:
      - Pyhon Fundamentals: lectures/python_fundamentals.md
      - Lecture 1: lectures/lecture_1.md
      - Lecture 2: lectures/lecture_2.md
      - Lecture 3: lectures/lecture_3.md
      - Lecture 4: lectures/lecture_4.md
      - Data Visualization: lectures/data_visualisation.md
      - Miscellaneous: lectures/misc.md